language: c
sudo: required
services:
  - docker
before_install:
  - docker build -t tbartelmess/libvault .
  - docker ps -a
  - docker run --name travis-container tbartelmess/libvault /bin/sh -c "/bin/bash -c \"trap : TERM INT; sleep infinity & wait\""
script:
  - docker exec travis-container cmake .
  - docker exec travis-container make
