language: c
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq curl check
  - curl -o install_cmake.sh https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.sh
  - chmod +x install_cmake.sh
  - mkdir /cmake
  - ./install_cmake.sh --skip-license --prefix=/cmake
script:
    - /cmake/bin/cmake .
    - make
    - make test
